### ISSUE TITLE
Mono Calibration on Ubuntu 16.04 with ros kinetic (OpenCV 3.1.0)

### ISSUE THREAD

**Issue by philipsgithub** [uzh-rpg/rpg_dvs_ros#13]
Hello DVS-Team,

I compiled the repo packages on Ubuntu 16.04 with ros kinetic (OpenCV 3.1.0). I had to adjust the parameter order of the stereoCalibrate-function in the file "camera_dvs_calibration.cpp" and change the import of QWidget in the file "calib_widget.py" (from ...QtGui to ...QtWidgets) to remove all compilation errors and to get a running mono calibration (dvs_intrinsic.launch).

But as soon as the dvs_128 detects the calibration-pattern (5x5 LEDs) some nodes die. It says:

OpenCV-Exception:
The function/feature is not implemented (You should explicitly call mapHost/unmapHost methods for ogl::Buffer object) in getMat_, file /tmp/binarydeb/ros-kinetic-opencv3-3.1.0/modules/core/src/matrix.cpp, line 1225

Ros-Error:
[roslaunch][ERROR] 2016-12-01 16:23:43,939: [dvs_calibration-4] process has died [pid 7488, exit code -6, cmd /home/fzi_pk/catkin_ws/devel/lib/dvs_calibration/mono events:=/dvs/events camera_info:=/dvs/camera_info set_camera_info:=/dvs/set_camera_info __name:=dvs_calibration __log:=/home/fzi_pk/.ros/log/184a092e-b7da-11e6-8d64-34e6ad58853b/dvs_calibration-4.log].

As for now we got stuck in debugging and probably going back to 14.04 with indigo but it would be nice to be able to use kinetic (+OpenCV 3). SO if you have some advises, would be great. Thank you very much.

Best Regards
Philip Keller

**Comment by eliasm** [comment]
The package should now work with both OpenCV 2 and 3 (and 14.04 and 16.04).

**Comment by epeefencer** [comment]
Why do you keep sending me email Elias Mueggler?
